### ISSUE TITLE
Замечания по lw2

### ISSUE THREAD

**Issue by ivklgn** [mrjayse/web2018_lw2#1]
1. Подобные вещи:
```css
#head-pics iframe, #head-pics img {
	margin: 0;
	width: auto;
	max-width: 50%;
	height: 100%;
	box-shadow: rgba(0,0,0,0.23) 0px 0px 15px 0.2px;
}
```
описывать на уровне id - не верно. ознакомьтесь с классами и наследованием

2. В html убито форматирование

3. Текст в:
```html
	<h2>Франция, Париж</h2>
	Металлическая башня с лестницами и лифтами к смотровым площадкам, построенная в 1889 году Гюставом Эйфелем.
```
текст рекомендуется брать в соответствующийх тег `<p>`

4. Данный блок разрознен без обрамляющего div
```html
	<div class="comment">
	  <b>Имя Фамилия</b> <span><a href="http://vk.com/">VK</a> | <a href="http://fb.com/">FB</a></span>
	  <p>С башни просто шикарный вид на Париж</p>
	</div>
	
	<div class="comment">
	  <b>Имя Фамилия</b> <span><a href="http://vk.com/">VK</a> | <a href="http://fb.com/">FB</a></span>
	  <p>С башни просто шикарный вид на Париж</p>
	</div>

	<div class="comment">
	  <b>Имя Фамилия</b> <span><a href="http://vk.com/">VK</a> | <a href="http://fb.com/">FB</a></span>
	  <p>С башни просто шикарный вид на Париж</p>
	</div>	
```
имеет смысл заключить это в `<div class="comments">` например
